version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=d6t5p59282ukia
      - POSTGRES_USER=juivwnkvrbclpq
      - POSTGRES_PASSWORD=f625e7227872ba8781d475b03ae603e9d4c863c9e48fb2e2bfbdcf27ffc02e6a
      - DATABASE_URL=ec2-52-71-161-140.compute-1.amazonaws.com
    volumes:
      - pgdata:/var/lib/postgresql/data

  doctory:
    build: ./doctory
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./doctory:/doctory
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_DB=doctory
      - POSTGRES_USER=doctory
      - POSTGRES_PASSWORD=postgres

  app:
    build: ./app
    command: yarn start
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"

volumes:
  pgdata:
